### ISSUE TITLE
MOB FIXES

### ISSUE THREAD

**Issue by HownerableSlowKnight** [AmethystGear/mirae#27]
reduce spawn rate of chests
make mobs guard chests
make it so that you cant run through mobs (even with ww)

**Comment by AmethystGear** [comment]
reduce chest spawn rate: chest spawn rate now reduced to 1%.
make mobs guard chests: fixed by structures, structures will have mobs spawn in front of chests to protect them
mobs will now stop you based on their aggression stat. An aggression of 1 means the mob will always stop you, an aggression of 0 means a mob will never stop you.
